修复命名规范导致的404
ZSCNetSupportDept/wiki pull request #10
Opened 2018-06-24 06:28 UTC by JerrySheh

2018-06-24 06:42 UTC, unlimitedsola requested changes
受kebab-case限制的只有文件名称，文档的标题和链接时的说明不需要更改

2018-06-24 06:42 UTC, unlimitedsola commented on fyoung-client.md
> +- [故障0-windows通信端口初始化失败](/article/fault/故障0-windows-通信端口初始化失败)
前面是可以用大写的
\[故障0-Windows通信端口初始化失败](/article/fault/故障0-windows-通信端口初始化失败)

2018-06-24 06:42 UTC, unlimitedsola commented on article/fault/故障0-获取到169-254开头的错误ip地址.md
> +<!-- TITLE: 故障0-获取到169-254开头的错误ip地址 -->
TITLE不受kebeb-case限制，我们只需要将文件重命名即可
这里还是
`<!-- TITLE: 故障0-获取到169.254开头的错误IP地址 -->`
好一点

2018-06-24 06:42 UTC, unlimitedsola commented on fyoung-client.md
> +- [故障0-获取到192-168开头的错误ip地址](/article/fault/故障0-获取到192-168开头的错误ip地址)
`[故障0-获取到192.168开头的错误IP地址](/article/fault/故障0-获取到192-168开头的错误ip地址)`

2018-06-24 06:42 UTC, unlimitedsola commented on fyoung-client.md
> +- [故障0-获取到169-254开头的错误ip地址](/article/fault/故障0-获取到169-254开头的错误ip地址)
同上

2018-06-24 06:42 UTC, unlimitedsola commented on article/fault/故障0-获取到192-168开头的错误ip地址.md
> +<!-- TITLE: 故障0-获取到192-168开头的错误ip地址 -->
同上

2018-06-27 10:22 UTC, Clovin commented
[这个文章](https://github.com/ZSCNetSupportDept/wiki/blob/master/article/fault/故障0-网络连接详细信息为空.md) 刚才我看图片引用失败，被我改动了，而且还加了个 Overview 栏，提交记得不要覆盖这个。。。

2018-06-27 17:35 UTC, merged